export { default as Profile } from "./Profile.svg"
export { default as ProfileFill } from "./ProfileFill.svg"
export { default as Trending } from "./Trending.svg"
export { default as Card } from "./Card.svg"
export { default as CardFill } from "./CardFill.svg"
export { default as Picture } from "./Image.svg"
export { default as PictureFill } from "./ImageFill.svg"